/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppActionsRouteImport } from './routes/app.actions'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppAudienceRouteImport } from './routes/app.audience'
import { Route as AppCatalogueRouteImport } from './routes/app.catalogue'
import { Route as AppOpportunitiesRouteImport } from './routes/app.opportunities'
import { Route as AppPerformanceRouteImport } from './routes/app.performance'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSocialRouteImport } from './routes/app.social'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActionsRoute = AppActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAudienceRoute = AppAudienceRouteImport.update({
  id: '/audience',
  path: '/audience',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogueRoute = AppCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSocialRoute = AppSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/app/actions': typeof AppActionsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/audience': typeof AppAudienceRoute
  '/app/catalogue': typeof AppCatalogueRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/social': typeof AppSocialRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/app/actions': typeof AppActionsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/audience': typeof AppAudienceRoute
  '/app/catalogue': typeof AppCatalogueRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/social': typeof AppSocialRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/app/actions': typeof AppActionsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/audience': typeof AppAudienceRoute
  '/app/catalogue': typeof AppCatalogueRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/social': typeof AppSocialRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/app/actions'
    | '/app/assistant'
    | '/app/audience'
    | '/app/catalogue'
    | '/app/opportunities'
    | '/app/performance'
    | '/app/settings'
    | '/app/social'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/app/actions'
    | '/app/assistant'
    | '/app/audience'
    | '/app/catalogue'
    | '/app/opportunities'
    | '/app/performance'
    | '/app/settings'
    | '/app/social'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/app/actions'
    | '/app/assistant'
    | '/app/audience'
    | '/app/catalogue'
    | '/app/opportunities'
    | '/app/performance'
    | '/app/settings'
    | '/app/social'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/actions': {
      id: '/app/actions'
      path: '/actions'
      fullPath: '/app/actions'
      preLoaderRoute: typeof AppActionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audience': {
      id: '/app/audience'
      path: '/audience'
      fullPath: '/app/audience'
      preLoaderRoute: typeof AppAudienceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/catalogue': {
      id: '/app/catalogue'
      path: '/catalogue'
      fullPath: '/app/catalogue'
      preLoaderRoute: typeof AppCatalogueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/opportunities': {
      id: '/app/opportunities'
      path: '/opportunities'
      fullPath: '/app/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/performance': {
      id: '/app/performance'
      path: '/performance'
      fullPath: '/app/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/social': {
      id: '/app/social'
      path: '/social'
      fullPath: '/app/social'
      preLoaderRoute: typeof AppSocialRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActionsRoute: typeof AppActionsRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppAudienceRoute: typeof AppAudienceRoute
  AppCatalogueRoute: typeof AppCatalogueRoute
  AppOpportunitiesRoute: typeof AppOpportunitiesRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSocialRoute: typeof AppSocialRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActionsRoute: AppActionsRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppAudienceRoute: AppAudienceRoute,
  AppCatalogueRoute: AppCatalogueRoute,
  AppOpportunitiesRoute: AppOpportunitiesRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSocialRoute: AppSocialRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
